### PR TITLE
Split services into separate components

### PR DESCRIPTION
**Pull request by fabianishere**
This pull request separates the (deployment) logic for each of the different services and groups functions of the same service.

### CODE REVIEW

**Comment by fabianishere** [comment]
Waiting for #17 to be merged first.

**Comment by fabianishere** [comment]
Rebasing on top of `master`.

**Comment by fabianishere** [comment]
Ready for review!

**Comment by tomdevman** [comment]
> Ready for review!

Could you merge the new features from master into this branch and fix the conflicts, thanks!

**Comment by fabianishere** [comment]
@cldme Done!

**Review by tomdevman — APPROVED** [review]
Good job! The setup looks really good now ! (feel free to merge it now)

**Pull request merged**
